pipeline {
    agent none
    // agent {
    //     docker {
    //         image 'python:2.7.16-slim'
    //         args '--user root'
    //     }
    // }


    stages{
        stage(build){

            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }

            when{
                changeset "**/vote/**"
            }


            steps{
                echo 'Compiling vote app..'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }

        stage(test){
            agent {
                docker {
                    image 'python:2.7.16-slim'
                    args '--user root'
                }
            }

            when{
                changeset "**/vote/**"
            }

            steps{
                echo 'Running Unit Tets on vote app..'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }

        stage("docker-package") {
            agent any
            when {
                // branch.matches("^master$")
                changeset "**/vote/**"
                branch 'master'
            }
            steps {
                echo 'Packaging vote app with docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-jovicons') {
                        def workerImage = docker.build("jovicons/vote:v${env.BUILD_ID}", "./vote")
                        workerImage.push()
                        // workerImage.push("${env.BRANCH_NAME}_latest")
                        workerImage.push("${env.BRANCH_NAME}_latest")
                    }
                }
            }
        }
    }

}