pipeline {
    // agent any
    //
    // tools {
    //     maven 'Maven 3.6.1'
    // }
    //
    
    agent {
        docker {
            image 'maven:3.6.1-jdk-8-slim'
            args '-v $HOME/.m2:/root/.m2' // save installation on disk
        }
    }

    stages {
        stage("build") {
            steps {
                echo 'Compiling worker app..'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }

        stage("test") {

            steps {
                echo 'Running Unit Tets on worker app..'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }

        stage("package") {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }

        stage("docker-package") {
            agent any
            steps {
                echo 'Packaging worker app with docker'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-jovicons') {
                        def workerImage = docker.build("jovicons/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}_latest")
                        workerImage.push("latest")
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}